export const games = [
	'A Plague Tale: Innocence',
	"Assassin's Creed",
	"Assassin's Creed II",
	"Assassin's Creed III",
	"Assassin's Creed IV: Black Flag",
	"Assassin's Creed: Brotherhood",
	"Assassin's Creed: Odyssey",
	"Assassin's Creed: Origins",
	"Assassin's Creed: Revelations",
	"Assassin's Creed: Rogue",
	"Assassin's Creed: Syndicate",
	"Assassin's Creed: Unity",
	'Battlefield 1',
	'Battlefield 3',
	'Battlefield 4',
	'Call of Duty',
	'Call of Duty: Black Ops',
	'Call of Duty: Black Ops II',
	'Call of Duty: Ghosts',
	'Call of Duty: Modern Warfare',
	'Call of Duty: Modern Warfare 2',
	'Call of Duty: Modern Warfare 3',
	'Call of Duty: WWII',
	'DmC: Devil May Cry',
	'Doom',
	'Far Cry 3',
	'Farm Frenzy 2',
	'Firewatch',
	'Ghost Recon: Future Soldier',
	'Gone Home',
	'Grand Theft Auto: Vice City',
	"Hellblade: Senua's Sacrifice",
	'Heroes of Hellas',
	'Inside',
	'Journey',
	'Limbo',
	"Mirror's Edge Catalyst",
	'Need for Speed: Most Wanted',
	'Need for Speed: Underground 2',
	'Prince of Persia: The Forgotten Sands',
	'Prince of Persia: The Two Thrones',
	'Prince of Persia: Warrior Within',
	'Quantum Break',
	'RiME',
	'Rise of the Tomb Raider',
	'Roads of Rome II',
	'Shadow of the Tomb Raider',
	'Spec Ops: The Line',
	'Tomb Raider',
	'Total Overdose',
	'Urban Freestyle Soccer',
	'Virtua Cop 2'
];
