export const completedGames: string[] = [
	'A Plague Tale: Innocence',
	"Assassin's Creed",
	"Assassin's Creed II",
	"Assassin's Creed III",
	"Assassin's Creed III: Liberation",
	"Assassin's Creed IV: Black Flag",
	"Assassin's Creed IV: Black Flag - Freedom Cry",
	"Assassin's Creed: Brotherhood",
	"Assassin's Creed: Odyssey",
	"Assassin's Creed: Origins",
	"Assassin's Creed: Revelations",
	"Assassin's Creed: Rogue",
	"Assassin's Creed: Syndicate",
	"Assassin's Creed: Unity",
	'Battlefield 1',
	'Battlefield 3',
	'Battlefield 4',
	'Battlefield V',
	'Call of Duty',
	'Call of Duty: Black Ops',
	'Call of Duty: Black Ops II',
	'Call of Duty: Ghosts',
	'Call of Duty: Modern Warfare',
	'Call of Duty: Modern Warfare 2',
	'Call of Duty: Modern Warfare 3',
	'Call of Duty: WWII',
	'Detroit: Become Human',
	'DmC: Devil May Cry',
	'Doom',
	'Far Cry 3',
	'Far Cry 4',
	'Farm Frenzy 2',
	'Firewatch',
	'Freedom Fighters',
	'Ghost Recon: Future Soldier',
	'Gone Home',
	'Grand Theft Auto: Vice City',
	"Hellblade: Senua's Sacrifice",
	'Heroes of Hellas',
	'Heroes of Hellas 2 - Olympia',
	'Heroes of Hellas 3 - Athens',
	'Hitman',
	'Hitman 2',
	'Inside',
	'Journey',
	'Life Is Strange',
	'Life Is Strange: Before the Storm',
	'Limbo',
	"Marvel's Avengers",
	"Mirror's Edge",
	"Mirror's Edge Catalyst",
	'Need for Speed: Most Wanted',
	'Need for Speed: Underground 2',
	'Prince of Persia: The Forgotten Sands',
	'Prince of Persia: The Sands of Time',
	'Prince of Persia: The Two Thrones',
	'Prince of Persia: Warrior Within',
	'Quantum Break',
	'Raji: An Ancient Epic',
	'RiME',
	'Rise of the Tomb Raider',
	'Roads of Rome II',
	'Scooby-Doo: Phantom of the Knight',
	'Sekiro: Shadows Die Twice',
	'Shadow of the Tomb Raider',
	'Spec Ops: The Line',
	'The Stanley Parable',
	'Tomb Raider',
	'Total Overdose',
	'Urban Freestyle Soccer',
	'Virtua Cop 2',
	'What Remains of Edith Finch'
].sort();

export const unfinishedGames: string[] = [
	'Among Us',
	'Ashes Cricket 2009',
	'Baba Is You',
	'Claw',
	'Counter-Strike 1.6',
	'Counter-Strike: Condition Zero',
	'Counter-Strike: Global Offensive',
	'Cricket 07',
	'Cricket 2000',
	'Far Cry 2',
	'FIFA',
	'Grand Theft Auto: San Andreas',
	'Grand Theft Auto III',
	'Hades',
	'Midtown Madness',
	'Need for Speed: Hot Pursuit',
	'Need for Speed: Porsche Unleashed',
	'Need for Speed: Underground',
	'Prince of Persia',
	'Roadrash',
	'We Happy Few',
	'WWE SmackDown vs. Raw'
].sort();
